swagger: "2.0"
info:
  version: 1.0.0
  title: ishtar-eve
  description: EVE Microservice for Ishtar consumption
basePath: /api
tags:
  - name: Market
    description: EVE Market endpoints
  - name: Wormhole
    description: EVE Wormhole endpoints
  - name: Specification
    description: API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  Price:
    type: object
    title: Price Result
    required:
      - min
      - max
      - avg
    properties:
      min:
        type: integer
      max:
        type: integer
      avg:
        type: integer
  PriceContainer:
    type: object
    title: Group of Sell/Buy Prices
    required:
      - sell
      - buy
    properties:
      sell:
        $ref: "#/definitions/Price"
      buy:
        $ref: "#/definitions/Price"
  MarketResult:
    type: object
    title: Market Price Result
    required:
      - id
      - name
      - group_id
      - price
    properties:
      id:
        type: integer
      name:
        type: string
      group_id:
        type: integer
      price:
        $ref: "#/definitions/PriceContainer"
  TheraResponse:
    type: object
    title: Closest Thera Entrance
    required:
      - jumps
      - system
      - security
      - region
      - theraSide
      - systemSide
    properties:
      jumps:
        type: string
      name:
        type: string
      security:
        type: integer
      region:
        type: string
      theraSide:
        type: string
      systemSide:
        type: string
  


paths:
  /market/price/name:
    get:
      tags:
        - Market
      description: Look up the price of an item by it's name.
      parameters:
        - name: name
          in: query
          required: true
          description: The Name of the item.
          type: string
        - name: strict
          in: query
          required: false
          description: Decides whether to use a strict search.
          type: boolean
      responses:
        200:
          description: Return an array of Market Results with all search results and their prices.
          schema: 
            $ref: "#/definitions/MarketResult"

  /market/price/id:
    get:
      tags:
        - Market
      description: Look up the price of an item by it's id.
      parameters:
        - name: id
          in: query
          required: true
          description: The type ID of the item.
          type: integer
      responses:
        200:
          description: Return the example with the specified id.
          schema: 
            $ref: "#/definitions/Price"
        400:
          description: No item by that typeid could be found.
        500:
          description: Some internal error has occured.

  /wormhole/thera:
    get:
      tags:
        - Wormhole
      description: Get the nearest thera entrance
      parameters:
        - name: systemName
          in: query
          required: true
          description: The name of the system.
          type: string
      responses:
        200:
          description: Return the nearest Thera entrance to the system.
          schema: 
            $ref: "#/definitions/TheraResponse"
        400:
          description: Invalid system name.
        500:
          description: Some internal error has occured.

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification