swagger: "2.0"
info:
  version: 1.0.0
  title: ishtar-eve
  description: EVE Microservice for Ishtar consumption
basePath: /api/v1
tags:
  - name: Market
    description: EVE Market endpoints

consumes:
  - application/json
produces:
  - application/json


definitions:
  Price:
    type: object
    title: Price Result
    required:
      - min
      - max
      - avg
    properties:
      min:
        type: integer
      max:
        type: integer
      avg:
        type: integer
  PriceContainer:
    type: object
    title: Group of Sell/Buy Prices
    required:
      - sell
      - buy
    properties:
      sell:
        $ref: "#/definitions/Price"
      buy:
        $ref: "#/definitions/Price"
  MarketResult:
    type: object
    title: Market Price Result
    required:
      - id
      - name
      - group_id
      - price
    properties:
      id:
        type: integer
      name:
        type: string
      group_id:
        type: integer
      price:
        $ref: "#/definitions/PriceContainer"
  


paths:
  /name:
    get:
      tags:
        - Market
      description: Look up the price of an item by it's name
      parameters:
        - name: name
          example: Vexor Navy Issue
          in: path
          required: true
          description: The Name of the item
          type: string
        - name: strict
          example: true
          in: path
          required: false
          description: Decides whether to use a strict search
          type: boolean
      responses:
        200:
          description: Return an array of Market Results with all search results and their prices.
          schema: 
            $ref: "#/definitions/MarketResult"

  /id:
    get:
      tags:
        - Market
      description: Look up the price of an item by it's id
      parameters:
        - name: id
          example: 17843
          in: path
          required: true
          description: The type ID of the item
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          schema: 
            $ref: "#/definitions/Price"
        400:
          description: No item by that typeid could be found
        500:
          description: Some internal error has occured

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification